name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/xnvme/xnvme-deps-alpine-latest:next

    steps:
      - name: Install Dependencies
        run: |
          apk add --no-cache bash wget
          wget https://sh.rustup.rs -O rustup-init
          chmod +x rustup-init
          ./rustup-init -y
          && rustup component add miri

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: source $HOME/.cargo/env
          echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $HOME/.bashrc
          cargo build --verbose

      - name: Test
        run: source $HOME/.cargo/env
          echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $HOME/.bashrc
          cargo test --verbose

      - name: Run tests with Miri
        run: |
          echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $HOME/.bashrc
          cargo +nightly miri test
