name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/xnvme/xnvme-deps-alpine-latest:next
    env:
      PKG_CONFIG_PATH: /opt/xnvme/lib/pkgconfig
      LD_LIBRARY_PATH: /opt/xnvme/lib

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          apk add --no-cache bash wget pkgconfig
          wget https://sh.rustup.rs -O rustup-init
          chmod +x rustup-init
          ./rustup-init -y --default-toolchain nightly
          source $HOME/.cargo/env
          rustup component add miri --toolchain nightly

      - name: Build
        run: |
          source $HOME/.cargo/env
          cargo build --verbose

      - name: Test
        run: |
          source $HOME/.cargo/env
          cargo test --verbose

      - name: Run tests with Miri
        run: |
          source $HOME/.cargo/env
          cargo miri test
